# This file was generated by GoReleaser. DO NOT EDIT.
cask "munch" do
  version "0.1.1"

  on_macos do
    sha256 "1e4322eae1ec6e303ba0cf43706c5f7b4f2f848567020849930770bbf8d0133b"
    url "https://github.com/KritR/munch/releases/download/v#{version}/munch_#{version}_darwin_universal.zip"
  end

  name "munch"
  desc "AI shell command widget for Zsh and Fish"
  homepage "https://github.com/KritR/munch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "munch"

  # No zap stanza required

end
